### ISSUE TITLE
Fix white background on right side panel

### ISSUE THREAD

**Issue by Otiel** [0x0049/Rocket.Chat.Dark#3]
The contextual bar (right side panel) background is white when it should be the same color as the left side panel:

![image](https://user-images.githubusercontent.com/3851902/36425333-c39deb30-1646-11e8-927c-00dd9a0202cb.png)
![image](https://user-images.githubusercontent.com/3851902/36425468-361d2ffe-1647-11e8-8262-4ee1b68ce4f8.png)
![image](https://user-images.githubusercontent.com/3851902/36425464-2ff8ef8c-1647-11e8-8952-63d11fbb2ecc.png)
![image](https://user-images.githubusercontent.com/3851902/36425455-251b9484-1647-11e8-8555-0e9ba5596fdb.png)

Channel specific panels:

![image](https://user-images.githubusercontent.com/3851902/36425630-a62e58e0-1647-11e8-9594-12aada8b3266.png)
![image](https://user-images.githubusercontent.com/3851902/36425607-9ccd220e-1647-11e8-8453-e5fb14ab67de.png)

**Comment by Pelogren** [comment]
I recently took the liberty to tweak the (previous) version of this template - it fixes the sidebar, but also does some other stuff (e.g. changes the look of the text-input field).
Unfortunately I am not exactly a less pro, so all I did was add some custom stuff to the .css file.

It looks like this
![Image](https://photos-3.dropbox.com/t/2/AACKeDq-ORt23M-2wxEOPWjgC64prkvvVE6w0kOCuJmV4A/12/19736383/jpeg/32x32/3/1519153200/0/2/chat.jpg/EPz04w4YiasIIAIoAg/FB4B3rMu9-yRmt1T3J30Q18d76Sh5WlegvxBVfSRg9U?dl=0&size=2048x1536&size_mode=3)

```css
/*custom stuff*/
#icon-menu {
    fill: #c2c3c5;
}
#icon-team {
    fill: #c2c3c5;
}
#icon-user-plus {
    fill: #c2c3c5;
}
#icon-send path {
    fill: #c2c3c5;
}
#icon-add-reaction {
    color: #c2c3c5;
}
#icon-lock, #icon-hashtag {
    color: #c2c3c5;
}
#icon-at, #icon-cross, .rc-tags__tag-text {
    color: #c2c3c5;
}
.reactions > li {
	background-color: #888889;
}
.rc-header__name, .rc-message-box__typing__user, .create-channel__title {
  color: #fff;
}
.rc-input__wrapper, .rc-tags  {
  border: none;
}
.rc-message-box__container{
  border: none;
  border-bottom: 1px solid #7289da;
}
.rc-button--primary {
 background-color: #7289da; 
}
.rc-button--outline {
  border-color: #c2c3c5;
  color: #c2c3c5;
}
.rc-input__title, .rc-form-legend, .rc-form-label, .rc-switch__text, .rc-member-list__counter {
  color: #c2c3c5;
}
.rc-tags__tag {
  background-color: #424449;
}
.contextual-bar__content {
 background-color: #2f343d; 
}
.rc-member-list__user:hover {
 background-color: #444444; 
}
```
